### ISSUE TITLE
Input string was not in correct format

### ISSUE THREAD

**Issue by john681611** [akaAgar/briefing-room-for-dcs#544]
#### Mission and Template Zip: 

Mission modified: Y/N

**Comment by Kianoni** [comment]
Still in latest beta when trying to generate a campaing:

```
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Double.Parse(String s)
   at BriefingRoom4DCS.Campaign.CampaignGenerator.GenerateAsync(CampaignTemplate campaignTemplate)
   at BriefingRoom4DCS.BriefingRoom.GenerateCampaignAsync(CampaignTemplate template) in D:\a\briefing-room-for-dcs\briefing-room-for-dcs\Source\BriefingRoom\BriefingRoom.cs:line 184
   at BriefingRoom4DCS.GUI.Common.Pages.CampaignBuilder.GenerateCampaign() in D:\a\briefing-room-for-dcs\briefing-room-for-dcs\Source\BriefingRoomCommonGUI\Pages\CampaignBuilder.razor:line 464
```

**Comment by john681611** [comment]
Can you provide an example template this happens on please

**Comment by Kianoni** [comment]
[Briefing room Campaing.txt](https://github.com/akaAgar/briefing-room-for-dcs/files/10173842/Briefing.room.Campaing.txt)

**Comment by john681611** [comment]
Please try against this beta: https://github.com/akaAgar/briefing-room-for-dcs/releases/tag/beta-release-221207-0812 If you can run web and post the error message that comes out on the console.

**Comment by john681611** [comment]
@Kianoni is the OS your using natively use a `,` for decimals rather than `.`?

**Comment by Kianoni** [comment]
@john681611 well of course, my locale is set to Finnish which breaks it. Can't believe this happens on C# code https://youtu.be/65WoL6e728Q

**Comment by john681611** [comment]
Welcome to Microsoft. I think I've fixed it in the next beta as I found some parsing that wasn't set to ignore culture.
