### ISSUE TITLE
Error: Input string was not in a correct format.

### ISSUE THREAD

**Issue by Neodyn** [akaAgar/briefing-room-for-dcs#586]
### Brief Description: 
Building up a campain with the "Campaign Generator" 

### Expected: 
Get a Campaign 

#### Mission and Template Zip: 
This is my "Default.cbrt"
[Default.txt](https://github.com/akaAgar/briefing-room-for-dcs/files/10170193/Default.txt)

[debug.log](https://github.com/akaAgar/briefing-room-for-dcs/files/10170209/debug.log)

Mission modified: N

**Comment by john681611** [comment]
#544

**Comment by john681611** [comment]
Please try against this beta: https://github.com/akaAgar/briefing-room-for-dcs/releases/tag/beta-release-221207-0812 If you can run web and post the error message that comes out on the console.

**Comment by Neodyn** [comment]
Same problem.
Output web console:
Server Logs:
```
System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Double.Parse(String s)
   at BriefingRoom4DCS.Campaign.CampaignGenerator.GenerateAsync(CampaignTemplate campaignTemplate)
   at BriefingRoom4DCS.BriefingRoom.GenerateCampaignAsync(CampaignTemplate template) in D:\a\briefing-room-for-dcs\briefing-room-for-dcs\Source\BriefingRoom\BriefingRoom.cs:line 184
   at BriefingRoom4DCS.GUI.Common.Pages.CampaignBuilder.GenerateCampaign() in D:\a\briefing-room-for-dcs\briefing-room-for-dcs\Source\BriefingRoomCommonGUI\Pages\CampaignBuilder.razor:line 464
```

**Comment by john681611** [comment]
@Neodyn  is the OS your using natively use a , for decimals rather than .? I just fixed this in https://github.com/akaAgar/briefing-room-for-dcs/releases/tag/beta-release-221208-1812

**Comment by Neodyn** [comment]
@john681611 Great now the "Campaign Generator" ist running as expected. 
Yes my OS is using the German regional settings

Thx for the support!
