### ISSUE TITLE
Error: Could not find file '/app/Include/Yaml/Group/AircraftTankerNoTACAN.yml'.

### ISSUE THREAD

**Issue by Dragonius** [akaAgar/briefing-room-for-dcs#754]
### Brief Description: 
Error popup:
Error: Could not find file '/app/Include/Yaml/Group/AircraftTankerNoTACAN.yml'.

Problem is that in linux docker there is diffrence big and small letters

Suggested fix 1:
Rename /app/Include/Yaml/Group/AircraftTankerNOTACAN.yml'  -> /app/Include/Yaml/Group/AircraftTankerNoTACAN.yml'

Or 

suggested fix 2:
Change code that it calls /app/Include/Yaml/Group/AircraftTankerNOTACAN.yml' instead of /app/Include/Yaml/Group/AircraftTankerNoTACAN.yml'

Server Logs:

warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]

      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.

System.IO.FileNotFoundException: Could not find file '/app/Include/Yaml/Group/AircraftTankerNoTACAN.yml'.

File name: '/app/Include/Yaml/Group/AircraftTankerNoTACAN.yml'

   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)

   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)

   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)

   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)

   at System.IO.File.ReadAllText(String path, Encoding encoding)

   at BriefingRoom4DCS.Generator.UnitMaker.CreateGroup(String groupTypeLua, Coordinates coordinates, String groupName, Boolean hidden, UnitFamily unitFamily, DBEntryJSONUnit firstUnitDB, Dictionary`2 extraSettings) in /source/Source/BriefingRoom/Generator/UnitMaker.cs:line 322

   at BriefingRoom4DCS.Generator.UnitMaker.AddUnitGroup(List`1 units, Side side, UnitFamily unitFamily, String groupTypeLua, String unitTypeLua, Coordinates coordinates, UnitMakerGroupFlags unitMakerGroupFlags, Dictionary`2 extraSettings) in /source/Source/BriefingRoom/Generator/UnitMaker.cs:line 207

   at BriefingRoom4DCS.Generator.MissionGeneratorFeatures`1.AddMissionFeature(T featureDB, DCSMission mission, Nullable`1 coordinates, Nullable`1 coordinates2, Dictionary`2& extraSettings, Nullable`1 objectiveTargetSide, Boolean hideEnemy, Nullable`1 preSelectedUnitFamily) in /source/Source/BriefingRoom/Generator/MissionGeneratorFeatures.cs:line 117

   at BriefingRoom4DCS.Generator.MissionGeneratorFeaturesMission.GenerateMissionFeature(DCSMission mission, String featureID, Coordinates initialCoordinates, Coordinates objectivesCenter) in /source/Source/BriefingRoom/Generator/MissionGeneratorFeaturesMission.cs:line 94

   at BriefingRoom4DCS.Generator.MissionGenerator.GenerateAsync(MissionTemplateRecord template) in /source/Source/BriefingRoom/Generator/MissionGenerator.cs:line 195

   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)

   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)

   at BriefingRoom4DCS.Generator.MissionGenerator.GenerateRetryableAsync(MissionTemplate template) in /source/Source/BriefingRoom/Generator/MissionGenerator.cs:line 244

   at BriefingRoom4DCS.Generator.CampaignGenerator.GenerateAsync(CampaignTemplate campaignTemplate) in /source/Source/BriefingRoom/Generator/CampaignGenerator.cs:line 60

   at BriefingRoom4DCS.BriefingRoom.GenerateCampaignAsync(CampaignTemplate template) in /source/Source/BriefingRoom/BriefingRoom.cs:line 195

   at BriefingRoom4DCS.GUI.Common.Pages.CampaignBuilder.GenerateCampaign() in /source/Source/BriefingRoomCommonGUI/Pages/CampaignBuilder.razor:line 494

### Expected: 
No error

#### Mission and Template Zip: 
No mission as it couldn't generate mission

Mission modified: Y/N

**Comment by john681611** [comment]
I'm not seeing this on the website version can you provide a template that regularly causes the error so I can test on docker and locally.

**Comment by Dragonius** [comment]
Area us South Atlantica, not let Sinai name fool you

**Comment by Dragonius** [comment]
EnemyTanker.ini has 

[UnitGroup]
Families=PlaneTankerBasket,PlaneTankerBoom
Flags=ImmediateAircraftActivation
Lua.Group=AircraftTankerNoTACAN <------ but in Filename is AircraftTankerNOTACAN.yml
Lua.Unit=Aircraft
Size=1,1
SpawnDistance=1.25
ValidSpawnPoints=Air

**Comment by Dragonius** [comment]
My system is on Virtualbox -> Debian 11  -> Docker -> briefing-room-for-dcs

**Comment by john681611** [comment]
Ok yayy I love dealing with Git and capitalisation changes in file names.

**Comment by john681611** [comment]
Corrected the damn github capitalisation bug. Fix should be in next beta.

**Comment by Dragonius** [comment]
Problem seemsto be gone away. thanks
